"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const main = read("public/assets/js/main.js");
const css = read("public/assets/css/styles.css");
const shell = read("app/views/pages/app-shell.php");
const api = read("api/index.php");
const register = read("public/auth/register.php");
const footer = read("app/views/layouts/footer.php");
const trendAnalysis = read("public/assets/js/lab-trend-analysis.js");
const envExample = read(".env.example");
const vercelConfig = JSON.parse(read("vercel.json"));
const vercelRouter = read("api/vercel.php");

assert.match(main, /data-add-result-parameter/);
assert.match(main, /data-remove-result-parameter/);
assert.match(main, /application\/pdf/);
assert.match(main, /data-rotate-result-image/);
assert.match(main, /Trying another image orientation/);
assert.match(main, /rotationCandidates/);
assert.match(main, /data-remove-result-source/);
assert.match(main, /data-include-result-source/);
assert.match(main, /OCR confidence/);
assert.match(main, /startNotificationPolling/);
assert.match(main, /glassDialog/);
assert.match(main, /type="button" data-drawer="result" data-id="\$\{result\.id\}">Review<\/button>/);
assert.match(main, /PAGE_CACHE_TTL/);
assert.match(main, /function trendAnalysisSection/);
assert.match(main, /data-trend-facility/);
assert.match(main, /Turnaround Time Trends/);
assert.match(main, /Flagged-result Trends/);
assert.match(footer, /lab-trend-analysis\.js/);
assert.match(trendAnalysis, /Above Reference Range/);
assert.match(main, /pageRequests: new Map\(\)/);
assert.match(main, /aria-current/);
assert.match(main, /function trapDrawerFocus/);
assert.match(main, /role="button" tabindex="0" aria-label="Open notification/);
assert.match(css, /\.maintenance-module-grid/);
assert.match(css, /@media \(max-width: 620px\)/);
assert.doesNotMatch(css, /Full Glassmorphism Theme/);
assert.match(css, /\.demo-login\s*\{/);
assert.doesNotMatch(shell, /\['section' => 'My account'\]/);
const adminShell = shell.slice(shell.indexOf("'Admin' => ["), shell.indexOf("'Doctor' => ["));
assert.doesNotMatch(adminShell, /'label' => 'Laboratory Tests'|'label' => 'Laboratory Requests'|'label' => 'Results'/);
assert.match(main, /data-drawer-password-toggle/);
assert.match(css, /\.drawer-password-wrap/);
assert.match(css, /\.popup-layer > \.drawer\s*\{[^}]*grid-template-rows:\s*auto minmax\(0, 1fr\)[^}]*overflow:\s*hidden/s);
assert.match(css, /\.popup-layer > \.drawer \.drawer-body\s*\{[^}]*min-height:\s*0[^}]*overflow-y:\s*auto/s);
assert.match(main, /class="form-grid user-form-grid"/);
assert.match(css, /\.popup-layer \.user-form-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/s);
assert.match(css, /@media \(max-width: 560px\)\s*\{\s*\.popup-layer \.user-form-grid\s*\{\s*grid-template-columns:\s*minmax\(0, 1fr\)/s);
assert.match(main, /function formatPhilippineMobile/);
assert.match(main, /placeholder="09XX-XXX-XXXX"/);
assert.match(main, /pattern="09\[0-9\]\{2\}-\[0-9\]\{3\}-\[0-9\]\{4\}"/);
assert.match(css, /\.user-compact-input\s*\{[^}]*260px/s);
assert.match(css, /\.form-field\.full:has\(\.user-compact-input\)\s*\{\s*grid-column:\s*auto/);
assert.match(api, /Use the contact number format 09XX-XXX-XXXX/);
assert.match(main, /All active facilities in the centralized laboratory network are available/);
assert.match(api, /Doctors can route a laboratory request to any active facility/);
assert.doesNotMatch(api, /Laboratory requests can only be submitted for your assigned active facility/);
assert.doesNotMatch(register, /Secure &amp; Private|All in One Place|Stay Informed/);
assert.doesNotMatch(footer, /vendor\/tesseract\/tesseract\.min\.js/);
assert.match(envExample, /URL_ENCODED_DATABASE_PASSWORD/);
assert.doesNotMatch(envExample, /postgresql:\/\/[^:\s]+:[^@\s]+@(?:db\.|aws-)/);
assert.doesNotMatch(envExample, /eyJhbGciOi/);
assert.match(vercelRouter, /str_starts_with\(\$relative, 'public\/'\)/);
assert.match(vercelRouter, /realpath\(\$publicRoot \. '\/' \. \$relative\)/);
assert.equal(vercelConfig.routes.filter((route) => route.src === "/assets/(.*)").length, 1);

console.log("UI contract tests passed.");
