-- Clinic System v2 - Supabase/PostgreSQL schema
-- Run in a new Supabase project's SQL Editor before deploying the application.
-- Existing projects: back up data first. This file intentionally does not drop tables.

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(60) NOT NULL UNIQUE,
  description VARCHAR(180),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS facilities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(160),
  status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_facilities_status ON facilities(status);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INTEGER NOT NULL REFERENCES roles(id),
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  avatar VARCHAR(8) NOT NULL,
  contact VARCHAR(40),
  status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role_id, status);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

CREATE TABLE IF NOT EXISTS patients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  patient_code VARCHAR(32) NOT NULL UNIQUE,
  date_of_birth DATE,
  sex VARCHAR(40),
  address VARCHAR(255),
  primary_facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,
  emergency_contact_name VARCHAR(120),
  emergency_contact_phone VARCHAR(40),
  privacy_acknowledged SMALLINT NOT NULL DEFAULT 1 CHECK (privacy_acknowledged IN (0, 1)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_patients_facility ON patients(primary_facility_id);

CREATE TABLE IF NOT EXISTS doctors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  specialty VARCHAR(120),
  assigned_facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,
  license_no VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS laboratory_staff (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  employee_no VARCHAR(80),
  default_facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,
  department VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_facilities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, facility_id)
);

CREATE TABLE IF NOT EXISTS test_definitions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  category VARCHAR(100) NOT NULL,
  sample_type VARCHAR(80) NOT NULL,
  turnaround_time VARCHAR(80) NOT NULL,
  price NUMERIC(10,2) NOT NULL DEFAULT 0,
  reference_range VARCHAR(180),
  instructions TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tests_status_category ON test_definitions(status, category);

CREATE TABLE IF NOT EXISTS lab_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(40) NOT NULL UNIQUE,
  patient_id INTEGER NOT NULL REFERENCES patients(id),
  doctor_id INTEGER NOT NULL REFERENCES users(id),
  facility_id INTEGER NOT NULL REFERENCES facilities(id),
  priority VARCHAR(40) NOT NULL DEFAULT 'Regular',
  status VARCHAR(60) NOT NULL DEFAULT 'Pending',
  clinical_notes TEXT,
  latest_update VARCHAR(180) NOT NULL DEFAULT 'Laboratory request submitted',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_orders_status ON lab_orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_doctor ON lab_orders(doctor_id);
CREATE INDEX IF NOT EXISTS idx_orders_patient ON lab_orders(patient_id);
CREATE INDEX IF NOT EXISTS idx_orders_facility ON lab_orders(facility_id);

CREATE TABLE IF NOT EXISTS lab_order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES lab_orders(id) ON DELETE CASCADE,
  test_definition_id INTEGER REFERENCES test_definitions(id) ON DELETE SET NULL,
  test_name VARCHAR(160) NOT NULL,
  status VARCHAR(60) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON lab_order_items(order_id);

CREATE TABLE IF NOT EXISTS lab_results (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_number VARCHAR(40) NOT NULL UNIQUE,
  order_id INTEGER NOT NULL REFERENCES lab_orders(id) ON DELETE CASCADE,
  uploaded_by INTEGER NOT NULL REFERENCES users(id),
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status VARCHAR(60) NOT NULL DEFAULT 'Pending Review',
  findings TEXT,
  remarks TEXT,
  rejected_reason TEXT,
  verified_at TIMESTAMP,
  released_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_results_status ON lab_results(status);
CREATE INDEX IF NOT EXISTS idx_results_order ON lab_results(order_id);

CREATE TABLE IF NOT EXISTS lab_result_values (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id INTEGER NOT NULL REFERENCES lab_results(id) ON DELETE CASCADE,
  test_definition_id INTEGER REFERENCES test_definitions(id) ON DELETE SET NULL,
  parameter_name VARCHAR(120) NOT NULL,
  value_text VARCHAR(120) NOT NULL,
  unit VARCHAR(60),
  reference_range VARCHAR(120),
  flag VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS result_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id INTEGER NOT NULL REFERENCES lab_results(id) ON DELETE CASCADE,
  original_name VARCHAR(180) NOT NULL,
  stored_name VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  size_bytes INTEGER NOT NULL DEFAULT 0,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clinical_notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id INTEGER NOT NULL REFERENCES lab_results(id) ON DELETE CASCADE,
  doctor_id INTEGER NOT NULL REFERENCES users(id),
  note TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notes_result ON clinical_notes(result_id);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  patient_id INTEGER REFERENCES patients(id) ON DELETE CASCADE,
  role_name VARCHAR(60),
  title VARCHAR(160) NOT NULL,
  message VARCHAR(255) NOT NULL,
  type_name VARCHAR(40) NOT NULL DEFAULT 'orders',
  related_order_id INTEGER REFERENCES lab_orders(id) ON DELETE SET NULL,
  related_result_id INTEGER REFERENCES lab_results(id) ON DELETE SET NULL,
  is_read SMALLINT NOT NULL DEFAULT 0 CHECK (is_read IN (0, 1)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_patient ON notifications(patient_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_role ON notifications(role_name, is_read);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  user_name VARCHAR(120) NOT NULL,
  role_name VARCHAR(60) NOT NULL,
  action VARCHAR(40) NOT NULL,
  module VARCHAR(80) NOT NULL,
  details VARCHAR(255) NOT NULL,
  ip_address VARCHAR(80) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_module ON audit_logs(module);

CREATE TABLE IF NOT EXISTS maintenance_settings (
  id INTEGER PRIMARY KEY,
  is_enabled SMALLINT NOT NULL DEFAULT 0 CHECK (is_enabled IN (0, 1)),
  scope VARCHAR(40) NOT NULL DEFAULT 'all',
  affected_roles TEXT,
  affected_pages TEXT,
  message VARCHAR(255) NOT NULL DEFAULT 'The system is currently undergoing maintenance. Please try again later.',
  reason VARCHAR(255),
  start_at TIMESTAMP,
  end_at TIMESTAMP,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_maintenance_enabled ON maintenance_settings(is_enabled);
CREATE INDEX IF NOT EXISTS idx_maintenance_created ON maintenance_settings(created_at);

CREATE TABLE IF NOT EXISTS system_settings (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- PHP sessions are stored here because Vercel functions do not share a local filesystem.
CREATE TABLE IF NOT EXISTS auth_sessions (
  token_hash CHAR(64) PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  csrf_token CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expiry ON auth_sessions(expires_at);

-- The browser never accesses application tables through PostgREST. Enabling RLS
-- without public policies prevents accidental anon-key access; server-side PDO
-- continues to connect with the project's database role.
DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'roles', 'facilities', 'users', 'patients', 'doctors', 'laboratory_staff',
    'staff_facilities', 'test_definitions', 'lab_orders', 'lab_order_items',
    'lab_results', 'lab_result_values', 'result_files', 'clinical_notes',
    'notifications', 'audit_logs', 'maintenance_settings', 'system_settings', 'auth_sessions'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION clinic_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'facilities', 'users', 'patients', 'doctors', 'laboratory_staff',
    'test_definitions', 'lab_orders', 'lab_results', 'maintenance_settings', 'system_settings'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS clinic_updated_at ON %I', table_name);
    EXECUTE format(
      'CREATE TRIGGER clinic_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION clinic_set_updated_at()',
      table_name
    );
  END LOOP;
END;
$$;

-- Result attachments remain private. The application issues short-lived signed URLs.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'lab-results',
  'lab-results',
  FALSE,
  10485760,
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

INSERT INTO maintenance_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Preserve the application's display-time behavior for new pooled connections.
ALTER ROLE postgres SET timezone = 'Asia/Manila';
