BEGIN;

UPDATE users
SET password_hash = CASE password_hash
  WHEN 'cms-demo-sha256$240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9' THEN '$2y$12$BjBVgvhl/4L7UNYkqqg8Ye3Cnz3yCgRILQrDzeLiHMFXrzvmD6VVO'
  WHEN 'cms-demo-sha256$f348d5628621f3d8f59c8cabda0f8eb0aa7e0514a90be7571020b1336f26c113' THEN '$2y$12$53pTfdXLy7rocyC4zvpL4OrEaq2MVXxfqWxf3GdaZAc8sSYEEE.sC'
  WHEN 'cms-demo-sha256$3705b578e8fcb1b82a94ad917881ec248bbd4111645e91aed3c19af12d82116f' THEN '$2y$12$wWI3.w6LCHT8tHrNjCG8.OelA3kd3iGSODCsznlPlA1hNYRbzOKhy'
  WHEN 'cms-demo-sha256$d4587ea9ead060c13fd994f21ecfa7926272a78854a2c20136b10a3c9e53e71e' THEN '$2y$12$4u299uVHERBDy80D0uv9GulSOfswcQ2ww1CJTKNFZGJ1Pt.FLPemS'
  ELSE password_hash
END
WHERE password_hash LIKE 'cms-demo-sha256$%';

CREATE TABLE IF NOT EXISTS auth_login_attempts (
  key_hash CHAR(64) PRIMARY KEY,
  attempts INTEGER NOT NULL DEFAULT 0,
  window_started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  blocked_until TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_blocked
  ON auth_login_attempts(blocked_until);

CREATE TABLE IF NOT EXISTS result_workflow_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id INTEGER NOT NULL REFERENCES lab_results(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(30) NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_result_workflow_result
  ON result_workflow_events(result_id, created_at);

ALTER TABLE auth_login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE result_workflow_events ENABLE ROW LEVEL SECURITY;

COMMIT;
